namespace BackendProjectTemplate.Application.Authentication.Features.RequestEmailConfirmationOtp;

public sealed record RequestEmailConfirmationOtpResponse(string Message, DateTimeOffset RetryAtUtc);
