global:
  scrape_interval: 5s

scrape_configs:
  - job_name: backend-template-webapi
    metrics_path: /metrics
    static_configs:
      - targets:
          - webapi:8080

  - job_name: backend-template-consumer
    metrics_path: /metrics
    static_configs:
      - targets:
          - consumer:8080
