/*
    Seeds [reference_data].[Countries] using Flagpedia country codes and flag URLs,
    and REST Countries dialing codes.
    Sources:
    - https://flagpedia.net/download/api
    - https://restcountries.com/

    CallingCode stores one canonical country calling code per country.
    The canonical value is the source root code.
*/
SET NOCOUNT ON;

DECLARE @UtcNow datetimeoffset = SYSUTCDATETIME();

MERGE [reference_data].[Countries] AS [Target]
USING
(
VALUES
    (N'AD', N'Andorra', N'+3', N'https://flagcdn.com/ad.svg'),
    (N'AE', N'United Arab Emirates', N'+9', N'https://flagcdn.com/ae.svg'),
    (N'AF', N'Afghanistan', N'+9', N'https://flagcdn.com/af.svg'),
    (N'AG', N'Antigua and Barbuda', N'+1', N'https://flagcdn.com/ag.svg'),
    (N'AI', N'Anguilla', N'+1', N'https://flagcdn.com/ai.svg'),
    (N'AL', N'Albania', N'+3', N'https://flagcdn.com/al.svg'),
    (N'AM', N'Armenia', N'+3', N'https://flagcdn.com/am.svg'),
    (N'AO', N'Angola', N'+2', N'https://flagcdn.com/ao.svg'),
    (N'AQ', N'Antarctica', N'', N'https://flagcdn.com/aq.svg'),
    (N'AR', N'Argentina', N'+5', N'https://flagcdn.com/ar.svg'),
    (N'AS', N'American Samoa', N'+1', N'https://flagcdn.com/as.svg'),
    (N'AT', N'Austria', N'+4', N'https://flagcdn.com/at.svg'),
    (N'AU', N'Australia', N'+6', N'https://flagcdn.com/au.svg'),
    (N'AW', N'Aruba', N'+2', N'https://flagcdn.com/aw.svg'),
    (N'AX', N'Åland Islands', N'+3', N'https://flagcdn.com/ax.svg'),
    (N'AZ', N'Azerbaijan', N'+9', N'https://flagcdn.com/az.svg'),
    (N'BA', N'Bosnia and Herzegovina', N'+3', N'https://flagcdn.com/ba.svg'),
    (N'BB', N'Barbados', N'+1', N'https://flagcdn.com/bb.svg'),
    (N'BD', N'Bangladesh', N'+8', N'https://flagcdn.com/bd.svg'),
    (N'BE', N'Belgium', N'+3', N'https://flagcdn.com/be.svg'),
    (N'BF', N'Burkina Faso', N'+2', N'https://flagcdn.com/bf.svg'),
    (N'BG', N'Bulgaria', N'+3', N'https://flagcdn.com/bg.svg'),
    (N'BH', N'Bahrain', N'+9', N'https://flagcdn.com/bh.svg'),
    (N'BI', N'Burundi', N'+2', N'https://flagcdn.com/bi.svg'),
    (N'BJ', N'Benin', N'+2', N'https://flagcdn.com/bj.svg'),
    (N'BL', N'Saint Barthélemy', N'+5', N'https://flagcdn.com/bl.svg'),
    (N'BM', N'Bermuda', N'+1', N'https://flagcdn.com/bm.svg'),
    (N'BN', N'Brunei', N'+6', N'https://flagcdn.com/bn.svg'),
    (N'BO', N'Bolivia', N'+5', N'https://flagcdn.com/bo.svg'),
    (N'BQ', N'Caribbean Netherlands', N'+5', N'https://flagcdn.com/bq.svg'),
    (N'BR', N'Brazil', N'+5', N'https://flagcdn.com/br.svg'),
    (N'BS', N'Bahamas', N'+1', N'https://flagcdn.com/bs.svg'),
    (N'BT', N'Bhutan', N'+9', N'https://flagcdn.com/bt.svg'),
    (N'BV', N'Bouvet Island', N'+4', N'https://flagcdn.com/bv.svg'),
    (N'BW', N'Botswana', N'+2', N'https://flagcdn.com/bw.svg'),
    (N'BY', N'Belarus', N'+3', N'https://flagcdn.com/by.svg'),
    (N'BZ', N'Belize', N'+5', N'https://flagcdn.com/bz.svg'),
    (N'CA', N'Canada', N'+1', N'https://flagcdn.com/ca.svg'),
    (N'CC', N'Cocos (Keeling) Islands', N'+6', N'https://flagcdn.com/cc.svg'),
    (N'CD', N'DR Congo', N'+2', N'https://flagcdn.com/cd.svg'),
    (N'CF', N'Central African Republic', N'+2', N'https://flagcdn.com/cf.svg'),
    (N'CG', N'Republic of the Congo', N'+2', N'https://flagcdn.com/cg.svg'),
    (N'CH', N'Switzerland', N'+4', N'https://flagcdn.com/ch.svg'),
    (N'CI', N'Côte d''Ivoire (Ivory Coast)', N'+2', N'https://flagcdn.com/ci.svg'),
    (N'CK', N'Cook Islands', N'+6', N'https://flagcdn.com/ck.svg'),
    (N'CL', N'Chile', N'+5', N'https://flagcdn.com/cl.svg'),
    (N'CM', N'Cameroon', N'+2', N'https://flagcdn.com/cm.svg'),
    (N'CN', N'China', N'+8', N'https://flagcdn.com/cn.svg'),
    (N'CO', N'Colombia', N'+5', N'https://flagcdn.com/co.svg'),
    (N'CR', N'Costa Rica', N'+5', N'https://flagcdn.com/cr.svg'),
    (N'CU', N'Cuba', N'+5', N'https://flagcdn.com/cu.svg'),
    (N'CV', N'Cape Verde', N'+2', N'https://flagcdn.com/cv.svg'),
    (N'CW', N'Curaçao', N'+5', N'https://flagcdn.com/cw.svg'),
    (N'CX', N'Christmas Island', N'+6', N'https://flagcdn.com/cx.svg'),
    (N'CY', N'Cyprus', N'+3', N'https://flagcdn.com/cy.svg'),
    (N'CZ', N'Czechia', N'+4', N'https://flagcdn.com/cz.svg'),
    (N'DE', N'Germany', N'+4', N'https://flagcdn.com/de.svg'),
    (N'DJ', N'Djibouti', N'+2', N'https://flagcdn.com/dj.svg'),
    (N'DK', N'Denmark', N'+4', N'https://flagcdn.com/dk.svg'),
    (N'DM', N'Dominica', N'+1', N'https://flagcdn.com/dm.svg'),
    (N'DO', N'Dominican Republic', N'+1', N'https://flagcdn.com/do.svg'),
    (N'DZ', N'Algeria', N'+2', N'https://flagcdn.com/dz.svg'),
    (N'EC', N'Ecuador', N'+5', N'https://flagcdn.com/ec.svg'),
    (N'EE', N'Estonia', N'+3', N'https://flagcdn.com/ee.svg'),
    (N'EG', N'Egypt', N'+2', N'https://flagcdn.com/eg.svg'),
    (N'EH', N'Western Sahara', N'+2', N'https://flagcdn.com/eh.svg'),
    (N'ER', N'Eritrea', N'+2', N'https://flagcdn.com/er.svg'),
    (N'ES', N'Spain', N'+3', N'https://flagcdn.com/es.svg'),
    (N'ET', N'Ethiopia', N'+2', N'https://flagcdn.com/et.svg'),
    (N'FI', N'Finland', N'+3', N'https://flagcdn.com/fi.svg'),
    (N'FJ', N'Fiji', N'+6', N'https://flagcdn.com/fj.svg'),
    (N'FK', N'Falkland Islands', N'+5', N'https://flagcdn.com/fk.svg'),
    (N'FM', N'Micronesia', N'+6', N'https://flagcdn.com/fm.svg'),
    (N'FO', N'Faroe Islands', N'+2', N'https://flagcdn.com/fo.svg'),
    (N'FR', N'France', N'+3', N'https://flagcdn.com/fr.svg'),
    (N'GA', N'Gabon', N'+2', N'https://flagcdn.com/ga.svg'),
    (N'GB', N'United Kingdom', N'+4', N'https://flagcdn.com/gb.svg'),
    (N'GD', N'Grenada', N'+1', N'https://flagcdn.com/gd.svg'),
    (N'GE', N'Georgia', N'+9', N'https://flagcdn.com/ge.svg'),
    (N'GF', N'French Guiana', N'+5', N'https://flagcdn.com/gf.svg'),
    (N'GG', N'Guernsey', N'+4', N'https://flagcdn.com/gg.svg'),
    (N'GH', N'Ghana', N'+2', N'https://flagcdn.com/gh.svg'),
    (N'GI', N'Gibraltar', N'+3', N'https://flagcdn.com/gi.svg'),
    (N'GL', N'Greenland', N'+2', N'https://flagcdn.com/gl.svg'),
    (N'GM', N'Gambia', N'+2', N'https://flagcdn.com/gm.svg'),
    (N'GN', N'Guinea', N'+2', N'https://flagcdn.com/gn.svg'),
    (N'GP', N'Guadeloupe', N'+5', N'https://flagcdn.com/gp.svg'),
    (N'GQ', N'Equatorial Guinea', N'+2', N'https://flagcdn.com/gq.svg'),
    (N'GR', N'Greece', N'+3', N'https://flagcdn.com/gr.svg'),
    (N'GS', N'South Georgia', N'+5', N'https://flagcdn.com/gs.svg'),
    (N'GT', N'Guatemala', N'+5', N'https://flagcdn.com/gt.svg'),
    (N'GU', N'Guam', N'+1', N'https://flagcdn.com/gu.svg'),
    (N'GW', N'Guinea-Bissau', N'+2', N'https://flagcdn.com/gw.svg'),
    (N'GY', N'Guyana', N'+5', N'https://flagcdn.com/gy.svg'),
    (N'HK', N'Hong Kong', N'+8', N'https://flagcdn.com/hk.svg'),
    (N'HM', N'Heard Island and McDonald Islands', N'', N'https://flagcdn.com/hm.svg'),
    (N'HN', N'Honduras', N'+5', N'https://flagcdn.com/hn.svg'),
    (N'HR', N'Croatia', N'+3', N'https://flagcdn.com/hr.svg'),
    (N'HT', N'Haiti', N'+5', N'https://flagcdn.com/ht.svg'),
    (N'HU', N'Hungary', N'+3', N'https://flagcdn.com/hu.svg'),
    (N'ID', N'Indonesia', N'+6', N'https://flagcdn.com/id.svg'),
    (N'IE', N'Ireland', N'+3', N'https://flagcdn.com/ie.svg'),
    (N'IL', N'Israel', N'+9', N'https://flagcdn.com/il.svg'),
    (N'IM', N'Isle of Man', N'+4', N'https://flagcdn.com/im.svg'),
    (N'IN', N'India', N'+9', N'https://flagcdn.com/in.svg'),
    (N'IO', N'British Indian Ocean Territory', N'+2', N'https://flagcdn.com/io.svg'),
    (N'IQ', N'Iraq', N'+9', N'https://flagcdn.com/iq.svg'),
    (N'IR', N'Iran', N'+9', N'https://flagcdn.com/ir.svg'),
    (N'IS', N'Iceland', N'+3', N'https://flagcdn.com/is.svg'),
    (N'IT', N'Italy', N'+3', N'https://flagcdn.com/it.svg'),
    (N'JE', N'Jersey', N'+4', N'https://flagcdn.com/je.svg'),
    (N'JM', N'Jamaica', N'+1', N'https://flagcdn.com/jm.svg'),
    (N'JO', N'Jordan', N'+9', N'https://flagcdn.com/jo.svg'),
    (N'JP', N'Japan', N'+8', N'https://flagcdn.com/jp.svg'),
    (N'KE', N'Kenya', N'+2', N'https://flagcdn.com/ke.svg'),
    (N'KG', N'Kyrgyzstan', N'+9', N'https://flagcdn.com/kg.svg'),
    (N'KH', N'Cambodia', N'+8', N'https://flagcdn.com/kh.svg'),
    (N'KI', N'Kiribati', N'+6', N'https://flagcdn.com/ki.svg'),
    (N'KM', N'Comoros', N'+2', N'https://flagcdn.com/km.svg'),
    (N'KN', N'Saint Kitts and Nevis', N'+1', N'https://flagcdn.com/kn.svg'),
    (N'KP', N'North Korea', N'+8', N'https://flagcdn.com/kp.svg'),
    (N'KR', N'South Korea', N'+8', N'https://flagcdn.com/kr.svg'),
    (N'KW', N'Kuwait', N'+9', N'https://flagcdn.com/kw.svg'),
    (N'KY', N'Cayman Islands', N'+1', N'https://flagcdn.com/ky.svg'),
    (N'KZ', N'Kazakhstan', N'+7', N'https://flagcdn.com/kz.svg'),
    (N'LA', N'Laos', N'+8', N'https://flagcdn.com/la.svg'),
    (N'LB', N'Lebanon', N'+9', N'https://flagcdn.com/lb.svg'),
    (N'LC', N'Saint Lucia', N'+1', N'https://flagcdn.com/lc.svg'),
    (N'LI', N'Liechtenstein', N'+4', N'https://flagcdn.com/li.svg'),
    (N'LK', N'Sri Lanka', N'+9', N'https://flagcdn.com/lk.svg'),
    (N'LR', N'Liberia', N'+2', N'https://flagcdn.com/lr.svg'),
    (N'LS', N'Lesotho', N'+2', N'https://flagcdn.com/ls.svg'),
    (N'LT', N'Lithuania', N'+3', N'https://flagcdn.com/lt.svg'),
    (N'LU', N'Luxembourg', N'+3', N'https://flagcdn.com/lu.svg'),
    (N'LV', N'Latvia', N'+3', N'https://flagcdn.com/lv.svg'),
    (N'LY', N'Libya', N'+2', N'https://flagcdn.com/ly.svg'),
    (N'MA', N'Morocco', N'+2', N'https://flagcdn.com/ma.svg'),
    (N'MC', N'Monaco', N'+3', N'https://flagcdn.com/mc.svg'),
    (N'MD', N'Moldova', N'+3', N'https://flagcdn.com/md.svg'),
    (N'ME', N'Montenegro', N'+3', N'https://flagcdn.com/me.svg'),
    (N'MF', N'Saint Martin', N'+5', N'https://flagcdn.com/mf.svg'),
    (N'MG', N'Madagascar', N'+2', N'https://flagcdn.com/mg.svg'),
    (N'MH', N'Marshall Islands', N'+6', N'https://flagcdn.com/mh.svg'),
    (N'MK', N'North Macedonia', N'+3', N'https://flagcdn.com/mk.svg'),
    (N'ML', N'Mali', N'+2', N'https://flagcdn.com/ml.svg'),
    (N'MM', N'Myanmar', N'+9', N'https://flagcdn.com/mm.svg'),
    (N'MN', N'Mongolia', N'+9', N'https://flagcdn.com/mn.svg'),
    (N'MO', N'Macau', N'+8', N'https://flagcdn.com/mo.svg'),
    (N'MP', N'Northern Mariana Islands', N'+1', N'https://flagcdn.com/mp.svg'),
    (N'MQ', N'Martinique', N'+5', N'https://flagcdn.com/mq.svg'),
    (N'MR', N'Mauritania', N'+2', N'https://flagcdn.com/mr.svg'),
    (N'MS', N'Montserrat', N'+1', N'https://flagcdn.com/ms.svg'),
    (N'MT', N'Malta', N'+3', N'https://flagcdn.com/mt.svg'),
    (N'MU', N'Mauritius', N'+2', N'https://flagcdn.com/mu.svg'),
    (N'MV', N'Maldives', N'+9', N'https://flagcdn.com/mv.svg'),
    (N'MW', N'Malawi', N'+2', N'https://flagcdn.com/mw.svg'),
    (N'MX', N'Mexico', N'+5', N'https://flagcdn.com/mx.svg'),
    (N'MY', N'Malaysia', N'+6', N'https://flagcdn.com/my.svg'),
    (N'MZ', N'Mozambique', N'+2', N'https://flagcdn.com/mz.svg'),
    (N'NA', N'Namibia', N'+2', N'https://flagcdn.com/na.svg'),
    (N'NC', N'New Caledonia', N'+6', N'https://flagcdn.com/nc.svg'),
    (N'NE', N'Niger', N'+2', N'https://flagcdn.com/ne.svg'),
    (N'NF', N'Norfolk Island', N'+6', N'https://flagcdn.com/nf.svg'),
    (N'NG', N'Nigeria', N'+2', N'https://flagcdn.com/ng.svg'),
    (N'NI', N'Nicaragua', N'+5', N'https://flagcdn.com/ni.svg'),
    (N'NL', N'Netherlands', N'+3', N'https://flagcdn.com/nl.svg'),
    (N'NO', N'Norway', N'+4', N'https://flagcdn.com/no.svg'),
    (N'NP', N'Nepal', N'+9', N'https://flagcdn.com/np.svg'),
    (N'NR', N'Nauru', N'+6', N'https://flagcdn.com/nr.svg'),
    (N'NU', N'Niue', N'+6', N'https://flagcdn.com/nu.svg'),
    (N'NZ', N'New Zealand', N'+6', N'https://flagcdn.com/nz.svg'),
    (N'OM', N'Oman', N'+9', N'https://flagcdn.com/om.svg'),
    (N'PA', N'Panama', N'+5', N'https://flagcdn.com/pa.svg'),
    (N'PE', N'Peru', N'+5', N'https://flagcdn.com/pe.svg'),
    (N'PF', N'French Polynesia', N'+6', N'https://flagcdn.com/pf.svg'),
    (N'PG', N'Papua New Guinea', N'+6', N'https://flagcdn.com/pg.svg'),
    (N'PH', N'Philippines', N'+6', N'https://flagcdn.com/ph.svg'),
    (N'PK', N'Pakistan', N'+9', N'https://flagcdn.com/pk.svg'),
    (N'PL', N'Poland', N'+4', N'https://flagcdn.com/pl.svg'),
    (N'PM', N'Saint Pierre and Miquelon', N'+5', N'https://flagcdn.com/pm.svg'),
    (N'PN', N'Pitcairn Islands', N'+6', N'https://flagcdn.com/pn.svg'),
    (N'PR', N'Puerto Rico', N'+1', N'https://flagcdn.com/pr.svg'),
    (N'PS', N'Palestine', N'+9', N'https://flagcdn.com/ps.svg'),
    (N'PT', N'Portugal', N'+3', N'https://flagcdn.com/pt.svg'),
    (N'PW', N'Palau', N'+6', N'https://flagcdn.com/pw.svg'),
    (N'PY', N'Paraguay', N'+5', N'https://flagcdn.com/py.svg'),
    (N'QA', N'Qatar', N'+9', N'https://flagcdn.com/qa.svg'),
    (N'RE', N'Réunion', N'+2', N'https://flagcdn.com/re.svg'),
    (N'RO', N'Romania', N'+4', N'https://flagcdn.com/ro.svg'),
    (N'RS', N'Serbia', N'+3', N'https://flagcdn.com/rs.svg'),
    (N'RU', N'Russia', N'+7', N'https://flagcdn.com/ru.svg'),
    (N'RW', N'Rwanda', N'+2', N'https://flagcdn.com/rw.svg'),
    (N'SA', N'Saudi Arabia', N'+9', N'https://flagcdn.com/sa.svg'),
    (N'SB', N'Solomon Islands', N'+6', N'https://flagcdn.com/sb.svg'),
    (N'SC', N'Seychelles', N'+2', N'https://flagcdn.com/sc.svg'),
    (N'SD', N'Sudan', N'+2', N'https://flagcdn.com/sd.svg'),
    (N'SE', N'Sweden', N'+4', N'https://flagcdn.com/se.svg'),
    (N'SG', N'Singapore', N'+6', N'https://flagcdn.com/sg.svg'),
    (N'SH', N'Saint Helena, Ascension and Tristan da Cunha', N'+2', N'https://flagcdn.com/sh.svg'),
    (N'SI', N'Slovenia', N'+3', N'https://flagcdn.com/si.svg'),
    (N'SJ', N'Svalbard and Jan Mayen', N'+4', N'https://flagcdn.com/sj.svg'),
    (N'SK', N'Slovakia', N'+4', N'https://flagcdn.com/sk.svg'),
    (N'SL', N'Sierra Leone', N'+2', N'https://flagcdn.com/sl.svg'),
    (N'SM', N'San Marino', N'+3', N'https://flagcdn.com/sm.svg'),
    (N'SN', N'Senegal', N'+2', N'https://flagcdn.com/sn.svg'),
    (N'SO', N'Somalia', N'+2', N'https://flagcdn.com/so.svg'),
    (N'SR', N'Suriname', N'+5', N'https://flagcdn.com/sr.svg'),
    (N'SS', N'South Sudan', N'+2', N'https://flagcdn.com/ss.svg'),
    (N'ST', N'São Tomé and Príncipe', N'+2', N'https://flagcdn.com/st.svg'),
    (N'SV', N'El Salvador', N'+5', N'https://flagcdn.com/sv.svg'),
    (N'SX', N'Sint Maarten', N'+1', N'https://flagcdn.com/sx.svg'),
    (N'SY', N'Syria', N'+9', N'https://flagcdn.com/sy.svg'),
    (N'SZ', N'Eswatini (Swaziland)', N'+2', N'https://flagcdn.com/sz.svg'),
    (N'TC', N'Turks and Caicos Islands', N'+1', N'https://flagcdn.com/tc.svg'),
    (N'TD', N'Chad', N'+2', N'https://flagcdn.com/td.svg'),
    (N'TF', N'French Southern and Antarctic Lands', N'+2', N'https://flagcdn.com/tf.svg'),
    (N'TG', N'Togo', N'+2', N'https://flagcdn.com/tg.svg'),
    (N'TH', N'Thailand', N'+6', N'https://flagcdn.com/th.svg'),
    (N'TJ', N'Tajikistan', N'+9', N'https://flagcdn.com/tj.svg'),
    (N'TK', N'Tokelau', N'+6', N'https://flagcdn.com/tk.svg'),
    (N'TL', N'Timor-Leste', N'+6', N'https://flagcdn.com/tl.svg'),
    (N'TM', N'Turkmenistan', N'+9', N'https://flagcdn.com/tm.svg'),
    (N'TN', N'Tunisia', N'+2', N'https://flagcdn.com/tn.svg'),
    (N'TO', N'Tonga', N'+6', N'https://flagcdn.com/to.svg'),
    (N'TR', N'Turkey', N'+9', N'https://flagcdn.com/tr.svg'),
    (N'TT', N'Trinidad and Tobago', N'+1', N'https://flagcdn.com/tt.svg'),
    (N'TV', N'Tuvalu', N'+6', N'https://flagcdn.com/tv.svg'),
    (N'TW', N'Taiwan', N'+8', N'https://flagcdn.com/tw.svg'),
    (N'TZ', N'Tanzania', N'+2', N'https://flagcdn.com/tz.svg'),
    (N'UA', N'Ukraine', N'+3', N'https://flagcdn.com/ua.svg'),
    (N'UG', N'Uganda', N'+2', N'https://flagcdn.com/ug.svg'),
    (N'UM', N'United States Minor Outlying Islands', N'+2', N'https://flagcdn.com/um.svg'),
    (N'US', N'United States', N'+1', N'https://flagcdn.com/us.svg'),
    (N'UY', N'Uruguay', N'+5', N'https://flagcdn.com/uy.svg'),
    (N'UZ', N'Uzbekistan', N'+9', N'https://flagcdn.com/uz.svg'),
    (N'VA', N'Vatican City (Holy See)', N'+3', N'https://flagcdn.com/va.svg'),
    (N'VC', N'Saint Vincent and the Grenadines', N'+1', N'https://flagcdn.com/vc.svg'),
    (N'VE', N'Venezuela', N'+5', N'https://flagcdn.com/ve.svg'),
    (N'VG', N'British Virgin Islands', N'+1', N'https://flagcdn.com/vg.svg'),
    (N'VI', N'United States Virgin Islands', N'+1', N'https://flagcdn.com/vi.svg'),
    (N'VN', N'Vietnam', N'+8', N'https://flagcdn.com/vn.svg'),
    (N'VU', N'Vanuatu', N'+6', N'https://flagcdn.com/vu.svg'),
    (N'WF', N'Wallis and Futuna', N'+6', N'https://flagcdn.com/wf.svg'),
    (N'WS', N'Samoa', N'+6', N'https://flagcdn.com/ws.svg'),
    (N'XK', N'Kosovo', N'+3', N'https://flagcdn.com/xk.svg'),
    (N'YE', N'Yemen', N'+9', N'https://flagcdn.com/ye.svg'),
    (N'YT', N'Mayotte', N'+2', N'https://flagcdn.com/yt.svg'),
    (N'ZA', N'South Africa', N'+2', N'https://flagcdn.com/za.svg'),
    (N'ZM', N'Zambia', N'+2', N'https://flagcdn.com/zm.svg'),
    (N'ZW', N'Zimbabwe', N'+2', N'https://flagcdn.com/zw.svg')
) AS [Source] ([ShortCode], [Name], [CallingCode], [FlagUrl])
ON [Target].[ShortCode] = [Source].[ShortCode]
WHEN MATCHED AND
(
    [Target].[Name] <> [Source].[Name]
    OR ISNULL([Target].[CallingCode], N'') <> ISNULL([Source].[CallingCode], N'')
    OR [Target].[FlagUrl] <> [Source].[FlagUrl]
)
THEN UPDATE SET
    [Name] = [Source].[Name],
    [CallingCode] = [Source].[CallingCode],
    [FlagUrl] = [Source].[FlagUrl],
    [UpdatedAtUtc] = @UtcNow
WHEN NOT MATCHED BY TARGET
THEN INSERT
(
    [Id],
    [ShortCode],
    [Name],
    [CallingCode],
    [FlagUrl],
    [CreatedAtUtc],
    [UpdatedAtUtc]
)
VALUES
(
    NEWID(),
    [Source].[ShortCode],
    [Source].[Name],
    [Source].[CallingCode],
    [Source].[FlagUrl],
    @UtcNow,
    @UtcNow
);

/*
    Seeds [notifications].[EmailProviders].

    Provider credentials and secrets should remain in configuration or a secret store.
    This table only controls the selectable provider definitions.
*/

MERGE [notifications].[EmailProviders] AS [Target]
USING
(
VALUES
    (N'Logging (Stub)', N'logging', 1),
    (N'Mailtrap', N'mailtrap', 0)
) AS [Source] ([ProviderName], [ProviderKey], [IsActive])
ON [Target].[ProviderKey] = [Source].[ProviderKey]
WHEN MATCHED AND
(
    [Target].[ProviderName] <> [Source].[ProviderName]
    OR [Target].[IsActive] <> [Source].[IsActive]
)
THEN UPDATE SET
    [ProviderName] = [Source].[ProviderName],
    [IsActive] = [Source].[IsActive],
    [UpdatedAtUtc] = @UtcNow
WHEN NOT MATCHED BY TARGET
THEN INSERT
(
    [Id],
    [ProviderName],
    [ProviderKey],
    [IsActive],
    [CreatedAtUtc],
    [UpdatedAtUtc]
)
VALUES
(
    NEWID(),
    [Source].[ProviderName],
    [Source].[ProviderKey],
    [Source].[IsActive],
    @UtcNow,
    @UtcNow
);
