using BackendProjectTemplate.Domain.Common.Auditing;

namespace BackendProjectTemplate.Application.Authentication.Features.StartGoogleAuthenticationFlow;

public sealed record StartGoogleAuthenticationFlowCommand(ActorContext ActorContext);
