using System.Text.Json.Serialization;

namespace BackendProjectTemplate.Infrastructure.Payments.SafeHaven;

public sealed record SafeHavenAccountStatementAccount(
    bool CanDebit,
    bool CanCredit,
    [property: JsonPropertyName("_id")] string Id,
    string Client,
    string AccountProduct,
    string AccountNumber,
    string AccountName,
    string AccountType,
    string CurrencyCode,
    string Bvn,
    decimal AccountBalance,
    decimal BookBalance,
    decimal InterestBalance,
    decimal WithHoldingTaxBalance,
    string Status,
    bool IsDefault,
    decimal NominalAnnualInterestRate,
    string InterestCompoundingPeriod,
    string InterestPostingPeriod,
    string InterestCalculationType,
    string InterestCalculationDaysInYearType,
    decimal MinRequiredOpeningBalance,
    int LockinPeriodFrequency,
    string LockinPeriodFrequencyType,
    bool AllowOverdraft,
    decimal OverdraftLimit,
    bool ChargeWithHoldingTax,
    bool ChargeValueAddedTax,
    bool ChargeStampDuty,
    SafeHavenAccountStatementNotificationSettings NotificationSettings,
    bool IsSubAccount,
    bool IsDeleted,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    [property: JsonPropertyName("__v")] int Version,
    string CbaAccountId);
